### ISSUE TITLE
Accidental notes

### ISSUE THREAD

**Issue by ern2150** [ern2150/FVCR#8]
Mary screenshot https://www.instagram.com/p/CKcZsJ4Bbec/?igshid=1gfic9ue3yepc

Gordon Ninja PTSD: https://youtu.be/FmKn_V25XKc?t=2418

This has lots of stream commercials but is in bad quality:
https://archive.org/details/jpcm39_August82

**Comment by ern2150** [comment]
Bad Beer Head: https://archive.org/details/JPCM_52_1988?start=918

might have CDer:
https://youtu.be/fQt_9Bgw2kg

handycam ad that has been in a few mixes : https://archive.org/details/SonyVideo8_1985

**Comment by ern2150** [comment]
Royal Warriors w music ids: https://youtu.be/QJAoIskM0RY

song used on 2/2/2020 https://www.youtube.com/watch?v=xvAmj3k3Imc

**Comment by ern2150** [comment]
David Sanborn’s the Dream underscores a Tokyo Broadcasting System recap of the 1988 Indy 500, which heavily features Rick Mears’ winning yellow number 5 car.

https://archive.org/details/JOKRTVSignOff19880539

**Comment by ern2150** [comment]
youtube video id=XXXXXXX

thumbnail=http://i3.ytimg.com/vi/XXXXXXX/hqdefault.jpg

**Comment by ern2150** [comment]
nothing to see here

**Comment by ern2150** [comment]
html markdown for elegant side-by-side images

 <a href="https://www.instagram.com/p/CLWuu3hBj6p/" title="Hanuman"><img src="https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/151260930_1194832644272114_5886965245463187723_n.jpg?_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=vWJipa-3bkAAX98T0Q5&tp=1&oh=c06c1f4370177644efd41ebc2187d184&oe=6059A566" width="50%"/></a><a href="https://www.instagram.com/p/CLWu6VwBBp-/" title="vs the Sun"><img src="https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/150434485_120854606609092_552732395316401348_n.jpg?_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=uFh_qcf30sUAX_q56rP&tp=1&oh=e6c67d2353abedc43de44a2f32ae4170&oe=6059712A" width="50%"/></a>

**Comment by ern2150** [comment]
neither here

**Comment by ern2150** [comment]
(empty comment to preserve history)

**Comment by ern2150** [comment]
(empty comment to preserve history again)

**Comment by ern2150** [comment]
(empty comment to preserve history a third time)

**Comment by ern2150** [comment]
Knife flipper and I Wanna Destroy You are from https://youtu.be/oWxm2Nuwya4 Advent Commando Angel blood Mission

**Comment by ern2150** [comment]
#35 Extra bits not on archive (or that I missed):

NTX - JOAX TV old school grid / target in the intro vortex

Green Ranger after Joseph Lai Lucas

Did I forget Chikara before Devo?

Weeble wobble and bad rap commercials after BIG EGG

Dino skele crazy art college commercial, ad for straw hat mohawk movie, Drew Barrymore movie... Sigfried and Roy, etc after OH after roadside assassin

Alternate roadside: "she is one of the 3 deadly assassins that we get an intro to in an IFD movie, I am not sure which one off the top of my head"

**Comment by ern2150** [comment]
Log manipulation for relative time
```
sed -n "/starttime/,/endtime/p" filename > snipped-content 
sed -n "/starttime/,/endtime/p" filename | cut -f 1 -d']' | cut -f 2 -d'['  | date -f - +%s | sed 's/$/ \- epochofstarttime/' | bc > snipped-relative
paste snipped-relative snipped-content > snipped-combined
```

**Comment by ern2150** [comment]
Hong Kong... Huh No matter where you hide out: [The Super Ninja at 55:03](https://youtu.be/2pJteYIJi5g?t=3303)

**Comment by ern2150** [comment]
Broken Codex

https://www.youtube.com/watch?v=eFp_WKsCjpA 9 Deaths of the Ninja
https://www.youtube.com/watch?v=XDCRBrogB2Q Boxer's Omen, The
https://www.youtube.com/watch?v=DCXU0aiZmBk Chinese Ghost Story, A
https://www.youtube.com/watch?v=-2b1XC-0KaU Iron Angels 2
https://www.youtube.com/watch?v=-7h-BmZhCsg Iron Angels 3
https://www.youtube.com/watch?v=vtQLXQAaExk Man Hunt
https://www.youtube.com/watch?v=Nprr6S9jqgo Mission: Kiss and Kill
https://www.youtube.com/watch?v=e5vXSA-VgvE Pagan Invasion Volume 1: Halloween: Trick or Treat?
https://www.youtube.com/watch?v=OOS0OSgl6z0 Pembalasan Rambu / The Intruder
https://www.youtube.com/watch?v=5WZbabatWtI Shadow Ninja / Ghost of the Ninja / Killer Wears White
https://www.youtube.com/watch?v=QEEuLHLWR6I  Sukeban Deka
https://www.youtube.com/watch?v=CCRgd_zifGY Sukeban Deka: Kazama Sanshimai No Gyakushû
https://www.youtube.com/watch?v=UhkRCcbN00M Unforgettable Fantasy
https://www.youtube.com/watch?v=c50unnENBoo Yokai Monsters: Spook Warfare

**Comment by ern2150** [comment]
Testing a Google Sheets doc for dead links:

```
curl https://docs.google.com/spreadsheets/d/<spreadsheetID>/gviz/tq?tqx=out:csv -s 
  | awk -F "\",\"" '{gsub(/[ ]/,"");print $5 "#" $3}' 
  | grep "http" | awk -F "http" '{print "http" $2}' 
  | while read -r line; do streamlink -l error $line; done
```
You can attach that CSV conversion to any publicly-readable google sheets url.  This gives you text where fields are contained in double quotes and separated by commas, so you need to know the boundary string to split those fields (in case there's a comma inside the field itself).

This particular sheet has a video link in Column 5, and a video title in Column 3.  I decided to hash them together (while removing pesky whitespace) so later processes would ignore it and I could still retrieve the title when needed.

I then lazily grab the first url I see on each line and send it to `streamlink` which is a utility meant to watch various streaming video sources in VLC for example.  It also does a good job informing me of a page that _should_ have video streams, but _doesn't_ (and yet returns a 200 instead of an actual error code).  It does this in a "shallow" manner by just telling me what media streams are available, without actually trying to download them.

From this output I can further filter for "No playable streams found" to find the easy missing sources.

It's by no means perfect -- streamlink won't touch "protected" videos (which usually means there's NSFW content and you need to be signed into a streaming service before you can tell if it has any actual video), and it can't process archive.org top-level urls.

**Comment by ern2150** [comment]
https://www.youtube.com/channel/UCdPr_5ZM_X_pzh-C80rE9bA/videos

**Comment by ern2150** [comment]
Phil Spector Sound / Hey you kids https://youtu.be/Y0OOgPPZOAs?t=227

**Comment by ern2150** [comment]
16x9 5 md5s

desk 
ad082afe8724f37dd0ea0364a059202d   a6c07221ef15c2b8d66c1b07a7aa6d4f        68639d9fa889ef0e693d5a28ebc546cb        02c946fb6422380ccc5a28e114838316        be48f32c9e7d5f063d773d826e115498

ocean shores hang lung wave
0eaecd4fa597681b9c469d2dbcbe525a   aeb7decc7316f60019f87e7581840094        6ad40804215a00b123f4d7d6d9390cc5        4c4441d2fba67c241b3a2b55acb0f02b        e928622be40cbc6d0202ae517e371e4f

**Comment by ern2150** [comment]
https://www.youtube.com/watch?v=QKJI9LxskAw champ

https://www.youtube.com/watch?v=tJu3WOlOmeM CLS

**Comment by ern2150** [comment]
Ninjas vs Bruce Lee (concord of bruce) has Karnov graveyard and seaside handcuff creditless ending

**Comment by ern2150** [comment]
Ninja ... Dixon?

https://ninjadixon.blogspot.com/search?q=sorapong

**Comment by ern2150** [comment]
Hurry, open (blue jean monster) https://www.youtube.com/watch?v=CSr1tXAAd2s&t=4627s

**Comment by ern2150** [comment]
http://www.comeuppancereviews.net/2013/12/ninja-force-of-assassins-1988.html?m=1

Comeuppance reviews eh

**Comment by ern2150** [comment]
http://www.critcononline.com/action%20part%202.htm

**Comment by ern2150** [comment]
Hitman the Cobra has jukebox Changeman around 1:13:10 in best archive version by redfilearchive

**Comment by ern2150** [comment]
https://archive.org/details/zombie.-army.-1991 56:07 "need to get our shit together" "you better get your fat ass down here" from mixtape 86 around the 7 minute mark

**Comment by ern2150** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugins/twitch.py", line 894, in _get_hls_streams
    streams = TwitchHLSStream.parse_variant_playlist(
  File "/usr/local/lib/python3.9/site-packages/streamlink/stream/hls.py", line 710, in parse_variant_playlist
    res = cls._fetch_variant_playlist(session, url, **request_args)
  File "/usr/local/lib/python3.9/site-packages/streamlink/stream/hls.py", line 666, in _fetch_variant_playlist
    res = session.http.get(url, exception=OSError, **request_args)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugin/api/http_session.py", line 190, in request
    raise err from None  # TODO: fix this
OSError: Unable to open URL: https://usher.ttvnw.net/api/channel/hls/forgotten_vcr.m3u8?player=twitchweb&p=436170&type=any&allow_source=true&allow_audio_only=true&allow_spectre=false&sig=ba6b2cd013acf0203b1acd250754241c76660c89&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22forgotten_vcr%22%2C%22channel_id%22%3A91263301%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1697100491%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3Anull%2C%22user_ip%22%3A%22162.211.34.221%22%2C%22version%22%3A2%7D&fast_bread=True (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/streamlink_cli/main.py", line 929, in main
    handle_url()
  File "/usr/local/lib/python3.9/site-packages/streamlink_cli/main.py", line 549, in handle_url
    streams = fetch_streams_with_retry(plugin, retry_streams, retry_max)
  File "/usr/local/lib/python3.9/site-packages/streamlink_cli/main.py", line 471, in fetch_streams_with_retry
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python3.9/site-packages/streamlink_cli/main.py", line 449, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugin/plugin.py", line 366, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugins/twitch.py", line 930, in _get_streams
    return self._get_hls_streams_live()
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugins/twitch.py", line 875, in _get_hls_streams_live
    return self._get_hls_streams(url, restricted_bitrates)
  File "/usr/local/lib/python3.9/site-packages/streamlink/plugins/twitch.py", line 907, in _get_hls_streams
    raise PluginError(err) from err
TypeError: exception causes must derive from BaseException
```
